<?xml version="1.0"?>
<!-- Revolute-Revolute Manipulator -->
<robot name="delta_test" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Constants for robot dimensions -->
  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="width" value="0.05" /> <!-- Square dimensions (widthxwidth) of beams -->
  <xacro:property name="height1" value="0.05" /> <!-- base and end links -->

  <xacro:include filename="$(find simple_delta_robot_description)/urdf/delta_arm.xacro" />
  <xacro:include filename="$(find simple_delta_robot_description)/urdf/delta_robot.gazebo.xacro" />

  <!-- Used for fixing robot to Gazebo 'base_link' -->
  <link name="world"/>

  <joint name="fixed" type="fixed">
    <parent link="world"/>
    <child link="base_link"/>
    <origin xyz="0 0 2" rpy="0 0 0"/>
  </joint>

  <link name="base_link">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	      <cylinder length="${height1}" radius="${height1*2}"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	      <cylinder length="${height1}" radius="${height1*2}"/>
      </geometry>
      <material name="orange">
        <color rgba="${255/255} ${108/255} ${10/255} 1.0"/>
      </material>
    </visual>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="1"/>
      <inertia
	      ixx="0.1" ixy="0.0" ixz="0.0"
	      iyy="0.1" iyz="0.0"
	      izz="0.1"/>
    </inertial>
  </link>

  <xacro:delta_arm prefix="front_"/>

  <joint name="front_delta_arm_joint" type="revolute">
    <parent link="base_link"/>
    <child link="front_upper_link"/>
    <origin xyz="0.1 0 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.7"/>
    <limit lower="${-60*PI/180}" upper="${60*PI/180}" effort="6" velocity="8"/>
  </joint>

  <xacro:delta_arm prefix="right_"/>
  
  <joint name="right_delta_arm_joint" type="revolute">
    <parent link="base_link"/>
    <child link="right_upper_link"/>
    <origin xyz="-0.05 -0.0866 0" rpy="0 0 ${-120*PI/180}"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.7"/>
    <limit lower="${-60*PI/180}" upper="${60*PI/180}" effort="6" velocity="8"/>
  </joint>

  <xacro:delta_arm prefix="left_"/>

  <joint name="left_delta_arm_joint" type="revolute">
    <parent link="base_link"/>
    <child link="left_upper_link"/>
    <origin xyz="-0.05 0.0866 0" rpy="0 0 ${120*PI/180}"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.7"/>
    <limit lower="${-60*PI/180}" upper="${60*PI/180}" effort="6" velocity="8"/>
  </joint>

  <link name="end_link">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	      <cylinder length="${height1/4}" radius="${height1/2}"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	      <cylinder length="${height1/4}" radius="${height1/2}"/>
      </geometry>
      <material name="orange">
        <color rgba="${255/255} ${108/255} ${10/255} 1.0"/>
      </material>
    </visual>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.1"/>
      <inertia
	      ixx="0.001" ixy="0.0" ixz="0.0"
	      iyy="0.001" iyz="0.0"
	      izz="0.001"/>
    </inertial>
  </link>

  <joint name="front_end_joint" type="fixed">
    <parent link="front_lower_end_link"/>
    <child link="end_link"/>
    <origin xyz="-0.05 0 0" rpy="0 0 0"/>
  </joint>

  <link name="right_end_virtual_link">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.001"/>
      <inertia
        ixx="0.0001" ixy="0.0" ixz="0.0"
        iyy="0.0001" iyz="0.0"
        izz="0.0001"/>
    </inertial>
  </link>

  <joint name="right_end_virtual_joint" type="fixed">
    <parent link="end_link"/>
    <child link="right_end_virtual_link"/>
    <origin xyz="-0.025 -0.0433 0" rpy="0 0 ${-120*PI/180}"/>
  </joint>

  <link name="left_end_virtual_link">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.001"/>
      <inertia
        ixx="0.0001" ixy="0.0" ixz="0.0"
        iyy="0.0001" iyz="0.0"
        izz="0.0001"/>
    </inertial>
  </link>

  <joint name="left_end_virtual_joint" type="fixed">
    <parent link="end_link"/>
    <child link="left_end_virtual_link"/>
    <origin xyz="-0.025 0.0433 0" rpy="0 0 ${120*PI/180}"/>
  </joint>

  <gazebo>
    <joint name="right_end_joint" type="fixed">
      <parent>right_lower_end_link</parent>
      <child>right_end_virtual_link</child>
      <pose> 0 0 0 0 0 0 </pose>
    </joint>
    <joint name="left_end_joint" type="fixed">
      <parent>left_lower_end_link</parent>
      <child>left_end_virtual_link</child>
      <pose> 0 0 0 0 0 0 </pose>
    </joint>
  </gazebo>
</robot>
